#if UNITY_EDITOR
using System.IO;
using UnityEngine;

internal static class RosalinaGenerator
{
    public const string RosalinaFolderName = "Rosalina";
    public const string RosalinaGeneratedCodeFolderName = "AutoGenerated";

    /// <summary>
    /// Creates the auto generated code file path based on the given output file name.
    /// </summary>
    /// <param name="outputFileName">Output file name.</param>
    /// <returns>Auto generated file path.</returns>
    public static string BuildAutoGeneratedFilePath(string outputFileName)
    {
        string autogeneratedFolder = Path.Combine("Assets", RosalinaFolderName, RosalinaGeneratedCodeFolderName);

        if (!Directory.Exists(autogeneratedFolder))
        {
            Directory.CreateDirectory(autogeneratedFolder);
        }

        return Path.Combine(autogeneratedFolder, outputFileName);
    }

    /// <summary>
    /// Generates a C# script containing the bindings of the given UI document.
    /// </summary>
    /// <param name="document">UI Document.</param>
    /// <param name="outputFile">Output file.</param>
    /// <returns>Rosalina generation result.</returns>
    public static void GenerateBindings(UIDocumentAsset document, string outputFile)
    {
        IRosalinaGeneartor generator = document.UxmlDocument.IsEditorExtension ? 
            new RosalinaEditorWindowBindingsGeneartor() : 
            new RosalinaBindingsGenerator();

        // Try to get an instance of settings if the user has set these in Project Settings
        RosalinaSettings settings = RosalinaSettings.GetInstance() ?? new RosalinaSettings()
        {
            // Some defaults if the settings have never been created.
            IsEnabled = true,
            DefaultNamespace = string.Empty
        };

        // Only run if we're enabled.
        if (!settings.IsEnabled)
        {
            Debug.Log($"[Rosalina]: Unable to generate UI Bindings because Rosalina was disabled in settings.");
            Debug.Log($"[Rosalina]: You can re-enable Rosalina in Edit -> Project Settings -> Rosalina.");
            return;
        }

        Debug.Log($"[Rosalina]: Generating UI bindings for {document.FullPath}");
        RosalinaGenerationResult result = generator.Generate(document);
        result.Save(outputFile);
        Debug.Log($"[Rosalina]: Done generating: {document.Name} (output: {outputFile})");
    }

    /// <summary>
    /// Generates a C# script for the UI logic.
    /// </summary>
    /// <param name="document">UI Document asset information.</param>
    /// <param name="outputFile">Output file.</param>
    /// <returns>Rosalina generation result.</returns>
    public static void GenerateScript(UIDocumentAsset document, string outputFile)
    {
        IRosalinaGeneartor generator = document.UxmlDocument.IsEditorExtension ?
            new RosalinaEditorWindowScriptGenerator() :
            new RosalinaScriptGenerator();

        // Try to get an instance of settings if the user has set these in Project Settings
        RosalinaSettings settings = RosalinaSettings.GetInstance() ?? new RosalinaSettings()
        {
            // Some defaults if the settings have never been created.
            IsEnabled = true,
            DefaultNamespace = string.Empty
        };

        // Only run if we're enabled.
        if (!settings.IsEnabled)
        {
            Debug.Log($"[Rosalina]: Unable to generate UI script because Rosalina was disabled in settings.");
            Debug.Log($"[Rosalina]: You can re-enable Rosalina in Edit -> Project Settings -> Rosalina.");
            return;
        }


        Debug.Log($"[Rosalina]: Generating UI script for {outputFile}");

        RosalinaGenerationResult result = generator.Generate(document);
        result.Save(outputFile);

        Debug.Log($"[Rosalina]: Done generating: {document.Name} (output: {outputFile})");
    
    }
}
#endif